### ISSUE TITLE
can't install from pip (python2)

### ISSUE THREAD

**Issue by alex-quin-gabriel** [marc-hanheide/TMuLE#15]
```
rasberry@simulator:~$ pip install tmule
Collecting tmule
  Using cached https://files.pythonhosted.org/packages/28/2d/700838b74620bd16223ca0f9f73e960c20c93e80d0e39b6f1761e8a4eb1d/tmule-1.5.6.tar.gz
Collecting autobahn (from tmule)
  Using cached https://files.pythonhosted.org/packages/84/05/828b0c5a558b67c8afd64e233976553298688eee39c78de3a8c8cf98c91f/autobahn-19.11.2-py2.py3-none-any.whl
Collecting libtmux (from tmule)
  Using cached https://files.pythonhosted.org/packages/9d/2b/0354cad25a812b43181357167e574493b845093efb6811e6b98127d509b5/libtmux-0.8.3-py2.py3-none-any.whl
Collecting psutil (from tmule)
  Using cached https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz
Collecting pyyaml (from tmule)
  Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz
Collecting twisted (from tmule)
  Using cached https://files.pythonhosted.org/packages/4d/15/890ba1d83dc29ad71427ce5174d5963b84a25c8cf1973815107709fbb520/Twisted-20.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting web.py (from tmule)
  Using cached https://files.pythonhosted.org/packages/f9/5f/2d0eb552180157e546307f8884009db614f50d9fe01eab70d080944bbe2b/web.py-0.60.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HtQs3V/web.py/setup.py", line 7, in <module>
        from web import __version__
      File "web/__init__.py", line 4, in <module>
        from . import (  # noqa: F401
      File "web/db.py", line 771
        print("ERR:", str(sql_query), file=debug)
                                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HtQs3V/web.py/
```

**Comment by nikostsagk** [comment]
try `pip install -U pip`
