### ISSUE TITLE
Session ID is provided (or ignored) yet tmule complains

### ISSUE THREAD

**Issue by ksatyaki** [marc-hanheide/TMuLE#20]
Hello @marc-hanheide , 

Somehow I seem to suddenly get this error when running with tmule. 

```
Traceback (most recent call last):
  File "/usr/local/bin/tmule", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tmule/tmule.py", line 524, in main
    tmux.init()
  File "/usr/local/lib/python3.6/dist-packages/tmule/tmule.py", line 102, in init
    "session_name": self.session_name
  File "/usr/local/lib/python3.6/dist-packages/libtmux/common.py", line 317, in find_where
    return self.where(attrs)[0]
  File "/usr/local/lib/python3.6/dist-packages/libtmux/common.py", line 348, in where
    return list(filter(by, self.children))
  File "/usr/local/lib/python3.6/dist-packages/libtmux/server.py", line 188, in sessions
    return self.list_sessions()
  File "/usr/local/lib/python3.6/dist-packages/libtmux/server.py", line 183, in list_sessions
    return [Session(server=self, **s) for s in self._sessions]
  File "/usr/local/lib/python3.6/dist-packages/libtmux/server.py", line 183, in <listcomp>
    return [Session(server=self, **s) for s in self._sessions]
  File "/usr/local/lib/python3.6/dist-packages/libtmux/session.py", line 61, in __init__
    raise ValueError('Session requires a `session_id`')
ValueError: Session requires a `session_id`
```

I set session name inside my tmule config, doesn't work. 
I try to override it with the `--session` argument explicitly, doesn't work. 
I try without session (should default to `tmule`), doesn't work. 

Please help!

**Comment by marc-hanheide** [comment]
darn... which version have you got installed?

**Comment by ksatyaki** [comment]
Doing a `sudo pip3 install tmule` says: 

```
Requirement already satisfied: tmule in /usr/local/lib/python3.6/dist-packages (1.5.8)
```

**Comment by marc-hanheide** [comment]
I have tried to reproduce this, but all seems working for me. Can you
* share your config file 
* try if the problem also happens with e.g. https://github.com/marc-hanheide/TMuLE/blob/a2dff691c5769188324ba0e7ed60460f9bf99fee/tmule.yaml
* try in a python virtual env, just to make sure it's not a problem with your system

**Comment by ksatyaki** [comment]
Oops! The test config you provided works without problems. Must be an error in my config file. :-(
