### ISSUE TITLE
Problems with tmule when using zsh

### ISSUE THREAD

**Issue by ksatyaki** [marc-hanheide/TMuLE#7]
When using zsh, tmule might not work. The usual error looks like: 

```
Traceback (most recent call last):
  File "/usr/local/bin/tmule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tmule/tmule.py", line 375, in main
    tmux.launch_all_windows()
  File "/usr/local/lib/python2.7/dist-packages/tmule/tmule.py", line 127, in launch_all_windows
    self.launch_window(winconf['name'])
  File "/usr/local/lib/python2.7/dist-packages/tmule/tmule.py", line 113, in launch_window
    pane = window.select_pane('%s:%s.%d' % (window.session.name, window_name, pane_no))
AttributeError: 'NoneType' object has no attribute 'select_pane'
```

This is because the windows are renamed by zsh (or perhaps oh-my-zsh only?).
This is not really nice for tmule. So the solution is to force tmux to use bash.

Add these lines to your `~/.tmux.conf`
(If the file doesn't exist, create it.)
```
set -g default-command /bin/bash
set -g default-shell /bin/bash
```

Now tmule should work.

**Comment by marc-hanheide** [comment]
It's a problem with oh-my-zsh. Not really a bug of tmule but a side effect of renaming window titles in general with tmux.
