### ISSUE TITLE
tmule doesn't work on Python 3

### ISSUE THREAD

**Issue by VorpalBlade** [marc-hanheide/TMuLE#9]
Tmule doesn't work on Python 3. Given that Python 2 has end of life in January 2020 it might be time to start porting it to a modern version.

```
Traceback (most recent call last):
  File "/home/user/virtualenv/tmule/bin/tmule", line 11, in <module>
    load_entry_point('tmule==1.4.2', 'console_scripts', 'tmule')()
  File "/home/user/virtualenv/tmule/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/virtualenv/tmule/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/user/virtualenv/tmule/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/user/virtualenv/tmule/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/virtualenv/tmule/lib/python3.7/site-packages/tmule/__init__.py", line 1, in <module>
    from .tmule import *
  File "/home/user/virtualenv/tmule/lib/python3.7/site-packages/tmule/tmule.py", line 504
    print tmux.is_running(args.window)
             ^
SyntaxError: invalid syntax
```

**Comment by VorpalBlade** [comment]
After the above pull request, everything except for the web server functionality appears to work.

**Comment by marc-hanheide** [comment]
With 1.5.3 the core parts should now work with Python3. I leave this open until the webserver is also ported.
